# Site settings
title: Kimberly McCalpine
email: kimberly.mccalpine@outlook.com
url: https://KMcCalpine.github.io/cyber-portfolio
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech, incident response, risk assessment, mitigation"
skills: "Cybersecurity - Analyst- Pen Tester- AI Prompt Engineer"
meta_author: McCalpine Kimberly

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BEB7A4 #80B3FF
  primary-rgb: "0,0,0" #"128,179,255"
  secondary: FFFFFC #FD6E8A
  secondary-dark: 000000 #A2122F

# Footer settings
footer:
  copyright: Kimberly McCalpine
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: https://github.com/kmccalpine

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:kimberly.mccalpine@outlook.com

# Postal address (add as many lines as necessary)
location:
  - line: Roosevelt, NY 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
